model_name_or_path: "Qwen/Qwen2.5-7B-Instruct"
data_path: "./nancy_18.txt"
save_model_dir: "./saves/lora_nancy"

layer: 6
rewrite_module: "model.layers.{}.mlp.down_proj.weight"

lr: 5.0e-4
batch_size: 1
num_steps: 25
device: 0
